update=12/22/2018 8:07:08 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetITyp=0
NetIExt=.net
PkgIExt=.pkg
NetDir=
LibDir=
NetType=0
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=
UseCmpFile=1
PadDrill=0
PadDrillOvalY=0
PadSizeH=3
PadSizeV=0.85
PcbTextSizeV=2.032
PcbTextSizeH=1.524
PcbTextThickness=0.3048
ModuleTextSizeV=1.524
ModuleTextSizeH=1.524
ModuleTextSizeThickness=0.3048
SolderMaskClearance=0.254
SolderMaskMinWidth=0
DrawSegmentWidth=0.381
BoardOutlineThickness=0.381
ModuleOutlineThickness=0.1524
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=C:/Engineering/KiCAD_Libraries/PCB/Active
LibName12=C:/Engineering/KiCAD_Libraries/PCB/Battery
LibName13=C:/Engineering/KiCAD_Libraries/PCB/Connector
LibName14=C:/Engineering/KiCAD_Libraries/PCB/display
LibName15=C:/Engineering/KiCAD_Libraries/PCB/Electromechanical
LibName16=C:/Engineering/KiCAD_Libraries/PCB/FIDUCIAL
LibName17=C:/Engineering/KiCAD_Libraries/PCB/Fuse
LibName18=C:/Engineering/KiCAD_Libraries/PCB/Header
LibName19=C:/Engineering/KiCAD_Libraries/PCB/ohw-logo
LibName20=C:/Engineering/KiCAD_Libraries/PCB/Passive
LibName21=C:/Engineering/KiCAD_Libraries/PCB/Potentiometer
LibName22=C:/Engineering/KiCAD_Libraries/PCB/Power_Supply
LibName23=C:/Engineering/KiCAD_Libraries/PCB/RF_Modules
LibName24=C:/Engineering/KiCAD_Libraries/PCB/Switch
LibName25=C:/Engineering/KiCAD_Libraries/PCB/Terminal_Block
LibName26=C:/Engineering/KiCAD_Libraries/PCB/Test_Point
LibName27=C:/Engineering/KiCAD_Libraries/PCB/Wire_to_Board
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=PDF_Schematic/
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=
